import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import Content from '../components/Content'
import Find from '../components/Find'
import Layout from '../components/Layout'
import styles from '../styles/Home.module.css'

export default function Home() {

    const [ countries, setCountries ] = useState([]);

    useEffect(() => {
      fetch('https://restcountries.com/v3.1/all')
      .then( res => res.json())
      .then( data => {
        setCountries(data);
        console.log(data)
      })
    }, [])

  function FindByCountry( e ){

    if(e.target.value === ""){
      fetch(`https://restcountries.com/v3.1/all`)
      .then( res => res.json())
      .then( data => {
          setCountries(data);
          console.log(data)
      })
    }else{
      fetch(`https://restcountries.com/v3.1/name/${e.target.value}`)
      .then( res => res.json())
      .then( data => {
          setCountries(data);
          console.log(data)
      })
    }
  }
  function FindByRegion( e ){

    if(e.target.value === "default"){
      fetch(`https://restcountries.com/v3.1/all`)
      .then( res => res.json())
      .then( data => {
          setCountries(data);
          console.log(data)
      })
    }else{
      fetch(`https://restcountries.com/v3.1/region/${e.target.value}`)
      .then( res => res.json())
      .then( data => {
          setCountries(data);
          console.log(data)
      })
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Find findCountry={FindByCountry} findRegion={FindByRegion} />
        <Content AllCountries={countries} />
      </Layout>
    </div>
  )
}
